apiVersion: v1
kind: Service
metadata:
  labels:
    app: java-http-troubleshooting
  name: java-http-troubleshooting
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: java-http-troubleshooting